---
server:
  port: ${port:8000}
spring.security:
  user:
    password: passwrd
logging:
  level:
    com.bicjo.sample: DEBUG
#    org.springframework.security: DEBUG

spring.mustache:
  expose-request-attributes: true
  prefix: classpath:/templates/
  suffix: .html
  
example.bar.authentication.enabled: true
